apiVersion: v1
kind: Service
metadata:
  name: f6eaae66-b0da-432b-bd76-feb3ec20739a
  namespace: production
  labels:
    app: f6eaae66-b0da-432b-bd76-feb3ec20739a
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: f6eaae66-b0da-432b-bd76-feb3ec20739a
  type: ClusterIP
