apiVersion: v1
kind: Service
metadata:
  name: 90f8fe21-79ec-4e13-a5f2-adb3c61b1c2b
  namespace: production
  labels:
    app: 90f8fe21-79ec-4e13-a5f2-adb3c61b1c2b
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: 90f8fe21-79ec-4e13-a5f2-adb3c61b1c2b
  type: ClusterIP
