apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/85674638-2d1e-4aa4-b6ca-f1720ab6cbb6
    newTag: latest
