apiVersion: v1
kind: Service
metadata:
  name: c88330d5-7eab-44ee-9cf8-1786db7ddb67
  namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  labels:
    app: c88330d5-7eab-44ee-9cf8-1786db7ddb67
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: c88330d5-7eab-44ee-9cf8-1786db7ddb67
  type: ClusterIP
