apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/994850c8-2acd-48d8-9210-181b88b5e2ef
    newTag: latest
