apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/51934f4e-3027-4a30-b647-5cdf1c0db12a
    newTag: latest
