apiVersion: apps/v1
kind: Deployment
metadata:
  name: 372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
  namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  labels:
    app: 372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
  template:
    metadata:
      labels:
        app: 372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/372cb8c8-4882-4d60-b4a1-c86e4e7a39f8:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
