apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/1dedbb6b-7be5-4d4b-b48b-cf65f33bca69
    newTag: latest
