apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2cf68968-dfb2-4e14-97f3-c866779a812b
  namespace: production
  labels:
    app: 2cf68968-dfb2-4e14-97f3-c866779a812b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2cf68968-dfb2-4e14-97f3-c866779a812b
  template:
    metadata:
      labels:
        app: 2cf68968-dfb2-4e14-97f3-c866779a812b
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/2cf68968-dfb2-4e14-97f3-c866779a812b:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
