apiVersion: v1
kind: Service
metadata:
  name: 2cf68968-dfb2-4e14-97f3-c866779a812b
  namespace: production
  labels:
    app: 2cf68968-dfb2-4e14-97f3-c866779a812b
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: 2cf68968-dfb2-4e14-97f3-c866779a812b
  type: ClusterIP
