apiVersion: v1
kind: Service
metadata:
  name: b8fab2a3-e106-432c-8784-cf1dbac21524
  namespace: production
  labels:
    app: b8fab2a3-e106-432c-8784-cf1dbac21524
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: b8fab2a3-e106-432c-8784-cf1dbac21524
  type: ClusterIP
