apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/381c4c6a-36a3-4b83-91e8-fef958722783
    newTag: latest
