apiVersion: v1
kind: Service
metadata:
  name: fb41cd3b-90dd-45c2-bda2-105ff4a628aa
  namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  labels:
    app: fb41cd3b-90dd-45c2-bda2-105ff4a628aa
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: fb41cd3b-90dd-45c2-bda2-105ff4a628aa
  type: ClusterIP
