apiVersion: apps/v1
kind: Deployment
metadata:
  name: b77740b6-3e8b-4314-96a2-893b683b3370
  namespace: production
  labels:
    app: b77740b6-3e8b-4314-96a2-893b683b3370
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b77740b6-3e8b-4314-96a2-893b683b3370
  template:
    metadata:
      labels:
        app: b77740b6-3e8b-4314-96a2-893b683b3370
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/b77740b6-3e8b-4314-96a2-893b683b3370:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
