apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/b77740b6-3e8b-4314-96a2-893b683b3370
    newTag: latest
