apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1fb7fb1-e424-4da9-ba17-2eb66ae56510
  namespace: production
  labels:
    app: a1fb7fb1-e424-4da9-ba17-2eb66ae56510
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1fb7fb1-e424-4da9-ba17-2eb66ae56510
  template:
    metadata:
      labels:
        app: a1fb7fb1-e424-4da9-ba17-2eb66ae56510
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/a1fb7fb1-e424-4da9-ba17-2eb66ae56510:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
