apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/gitops-infra.git'
    targetRevision: HEAD
    path: manifests/372cb8c8-4882-4d60-b4a1-c86e4e7a39f8
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
