apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5c565c77-1595-4d39-8576-9de4e7c09a7d
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/5c565c77-1595-4d39-8576-9de4e7c09a7d.git'
    targetRevision: HEAD
    path: deploy/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
