apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 773faaea-400e-42d2-a8d4-e5192c85ad93
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/773faaea-400e-42d2-a8d4-e5192c85ad93.git'
    targetRevision: HEAD
    path: deploy/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
