apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 7c147f86-320d-4d62-ae8c-eff8a4baaebc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/7c147f86-320d-4d62-ae8c-eff8a4baaebc.git'
    targetRevision: HEAD
    path: deploy/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
