apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 90f8fe21-79ec-4e13-a5f2-adb3c61b1c2b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/gitops-infra.git'
    targetRevision: HEAD
    path: manifests/90f8fe21-79ec-4e13-a5f2-adb3c61b1c2b
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
