apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: f6eaae66-b0da-432b-bd76-feb3ec20739a
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/quymk1/f6eaae66-b0da-432b-bd76-feb3ec20739a
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:kustomize
    argocd-image-updater.argoproj.io/write-back-path: manifests/f6eaae66-b0da-432b-bd76-feb3ec20739a
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/gitops-infra.git'
    targetRevision: HEAD
    path: manifests/f6eaae66-b0da-432b-bd76-feb3ec20739a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
