apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fb41cd3b-90dd-45c2-bda2-105ff4a628aa
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/quymk1/fb41cd3b-90dd-45c2-bda2-105ff4a628aa
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:kustomize
    argocd-image-updater.argoproj.io/write-back-path: manifests/fb41cd3b-90dd-45c2-bda2-105ff4a628aa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/gitops-infra.git'
    targetRevision: HEAD
    path: manifests/fb41cd3b-90dd-45c2-bda2-105ff4a628aa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 5ecb31a3-809d-4c2e-819c-c1be164a23f1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
