apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service1-c2c68ef5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/quymk1/lkf-test-service1-c2c68ef5.git'
    targetRevision: HEAD
    path: deploy/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
