apiVersion: v1
kind: Service
metadata:
  name: add2b6f9-bdc8-46ed-a1e0-4df9bf377af9
  namespace: production
  labels:
    app: add2b6f9-bdc8-46ed-a1e0-4df9bf377af9
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: add2b6f9-bdc8-46ed-a1e0-4df9bf377af9
  type: ClusterIP
