apiVersion: apps/v1
kind: Deployment
metadata:
  name: e9bbe5f9-530a-4f58-8667-c0b21c98454c
  namespace: production
  labels:
    app: e9bbe5f9-530a-4f58-8667-c0b21c98454c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e9bbe5f9-530a-4f58-8667-c0b21c98454c
  template:
    metadata:
      labels:
        app: e9bbe5f9-530a-4f58-8667-c0b21c98454c
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/e9bbe5f9-530a-4f58-8667-c0b21c98454c:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
