apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/e9bbe5f9-530a-4f58-8667-c0b21c98454c
    newTag: latest
