apiVersion: apps/v1
kind: Deployment
metadata:
  name: 83b23203-c4a2-4bf7-8777-7d55ef349c00
  namespace: production
  labels:
    app: 83b23203-c4a2-4bf7-8777-7d55ef349c00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 83b23203-c4a2-4bf7-8777-7d55ef349c00
  template:
    metadata:
      labels:
        app: 83b23203-c4a2-4bf7-8777-7d55ef349c00
    spec:
      containers:
        - name: app
          image: ghcr.io/quymk1/83b23203-c4a2-4bf7-8777-7d55ef349c00:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
