apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/quymk1/83b23203-c4a2-4bf7-8777-7d55ef349c00
    newTag: latest
